openapi: 3.0.1
info:
  title: Sanitally webapp
  version: 1.0.0
  description: Medical appointment system
servers:
  - url: 'http://localhost:5000/api'
paths:
  /login:
    post:
      summary: login to the app
      parameters:
        - email: email
          in: body
          type: string
          required: true
        - password: password
          in: body
          required: true
          type: string
